server:
    do-ip6: no
    # tells unbound not to use ipv6 when talking to DNS
    # Why ? the docker netowrk in the compose 'dns-net' has no IPv6, so every IPv6 attempt would just fail and time out before Unbound falls back to IPv4.